export enum AuctionRoute {
	CREATE_AUCTION_RESPONSE = "CREATE_AUCTION_RESPONSE",
	CREATE_PRODUCT_RESPONSE = "CREATE_PRODUCT_RESPONSE",
	START_AUCTION_RESPONSE = "START_AUCTION_RESPONSE",
	TERMINATE_AUCTION_RESPONSE = "TERMINATE_AUCTION_RESPONSE"
	
}
