export enum DatabaseRoute {
	CREATE_AUCTION_REQUEST = "CREATE_AUCTION_REQUEST",
	START_AUCTION_REQUEST = "START_AUCTION_REQUEST",
	TERMINATE_AUCTION_REQUEST = "TERMINATE_AUCTION_REQUEST",
	PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST",
    LOGIN_WITH_ADDR = "LOGIN_WITH_ADDR",
}
