services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # RabbitMQ
      - "15672:15672"  # Management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

  event_queue:
    build:
      context: ./event-queue/
      dockerfile: Dockerfile
    ports:
      - "16231:16231"
volumes:
  rabbitmq_data:

